<a href="https://colab.research.google.com/github/Ishasolanki441/isha-/blob/main/predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

from sklearn.model_selection import train_test_split
home=np.array([100,200,300,400,500,600,700,800,900,1000])
price= np.array([2000,3000,4000,5000,6000,7000,8000,9000,11000,11500])
print(home)
print(price)
home_train, home_test, price_train, price_test = train_test_split(
 home,price, random_state=41, test_size=0.5, shuffle=True)
print("home_train:",home_train)
print("home_test:",home_test)
print("price_train:",price_train)
print("price_test:",price_test)



[ 100  200  300  400  500  600  700  800  900 1000]
[ 2000  3000  4000  5000  6000  7000  8000  9000 11000 11500]
home_train: [1000  300  500  400  100]
home_test: [600 700 800 900 200]
price_train: [11500  4000  6000  5000  2000]
price_test: [ 7000  8000  9000 11000  3000]


In [15]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
home=np.array([1,2,3,4,5])
price= np.array([200,300,400,500,600])
print(home)
print(price)
home_train, home_test, price_train, price_test = train_test_split(
 home,price, random_state=41, test_size=0.5, shuffle=True)
print("home_train:",home_train)
print("home_test:",home_test)
print("price_train:",price_train)
print("price_test:",price_test)
home_train = home_train.reshape(-1,1)
home_test = home_test.reshape(-1,1)
price_train = price_train.reshape(-1,1)
price_test = price_test.reshape(-1,1)
regr = LinearRegression()

regr.fit(home_train,price_train)
print(regr.score(home_test.reshape(-1,1),price_test,price_test.reshape(-1,1)))
print(regr.predict(home_test.reshape(-1,1)))

[1 2 3 4 5]
[200 300 400 500 600]
home_train: [4 1]
home_test: [2 3 5]
price_train: [500 200]
price_test: [300 400 600]
1.0
[[300.]
 [400.]
 [600.]]
